### ISSUE TITLE
Releases should be fully cross-versioned

### ISSUE THREAD

**Issue by lrytz** [cb372/scala-typed-holes#6]
Unlike scala-library.jar, the scala compiler is not binary compatible between minor releases. Therefore, compiler plugins should be released with full cross versioning, and a new release is needed for every minor Scala release. See https://github.com/scalamacros/paradise/blob/2.12.8/build.sbt for example, https://search.maven.org/search?q=g:org.scalamacros.

**Comment by cb372** [comment]
Thanks, that's a good point.

I was taking my lead on this from [kind-projector](https://github.com/non/kind-projector), which is not fully cross-versioned. Does that plugin need to be fixed in the same way? I assume it has simply "got lucky" so far and not run into any breaking changes in the compiler.

**Comment by lrytz** [comment]
I'd say so, yes.. Let's get a confirmation from @adriaanm or @retronym :)

**Comment by adriaanm** [comment]
Yep, we don't check binary compatibility at all between even minor compiler releases. You could get lucky if you stick within the parts of the compiler that rarely change anymore, but I wouldn't recommend it.

**Comment by cb372** [comment]
Thanks for confirming. I'll switch to full cross-versioning and also open an issue on kind-projector.
